additional:
  - action-commit-lint
  - action-semantic-release
  - action-workflow-queue

files:
  - "!**/template-sync.yml"
  - "!action.yml"
  - "!colophon.yml"
  - "!docs/README.md"
  - "!README.md"
  - "!Dockerfile"
  - "!action/*"
  - "!.env"
  - "!.github/dependabot.yml"
  - "!.github/workflows/*.yml"
  - .github/template/push.yml: .github/workflows/push.yml
  - .github/template/pull_request_target.yml: .github/workflows/pull_request_target.yml
  - .github/template/dependabot.yml: .github/dependabot.yml

