additional:
  - action-commit-lint
  - action-semantic-release

files:
  - "!**/template-sync.yml"
  - "!action.yml"
  - "!colophon.yml"
  - "!docs/README.md"
  - "!README.md"
  - "!Dockerfile"
  - "!action/*"
  - "!.env"
