name: GitHub Docker Action Template
description: A template for Docker-based GitHub Actions

branding:
  color: purple
  icon: monitor

inputs:
  github-token:
    description: The GitHub token used to post comments on pull requests
    default: ${{ secrets.GITHUB_TOKEN }}
    required: false

runs:
  using: docker
  image: docker://ghcr.io/ahmadnassri/:1.0.0
