# ---------------------------------------------------- #
# Note: this file originates in template-action-docker #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-action-docker.yml@master
    secrets: inherit
    permissions: write-all
